---
version: "3"

env:
  PYTHON: python3.12

tasks:
  default:
    cmds:
      - task: help

  bootstrap:
    desc: Bootstrap Python venv (requirements)
    cmds:
      - >
        $PYTHON -m venv .venv &&
        source .venv/bin/activate &&
        pip install --upgrade pip &&
        pip install -e .[dev] &&
        pip install -r tests/integration/requirements.txt

  reinit:
    desc: Reinitialization Python venv (requirements)
    cmds:
      - rm -rf .venv
      - task: bootstrap

  pipeline:
    desc: Simulate pipeline (lint, tests...)
    cmds:
      - yamllint --config-file .config/linters/yamllint.yml .
      - flake8 --config .config/linters/flake8.ini
      - pytest

  help:
    desc: Display help
    cmds:
      - task --list
