---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        linter: ["bandit", "djlint", "flake8", "mypy", "pylint", "yamllint"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install --upgrade pip && pip install -e .[dev,lint,test]

      - name: Run linter ${{ matrix.linter }}
        run: task lint:${{ matrix.linter }}
