---
name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        linter: ["bandit", "djlint", "flake8", "mypy", "pylint", "yamllint"]
    env:
      TASK_VERSION: 3.32.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          wget https://github.com/go-task/task/releases/download/v$TASK_VERSION/task_linux_amd64.deb
          sudo dpkg -i task_linux_amd64.deb
          task bootstrap

      - name: Run linter ${{ matrix.linter }}
        run: task lint:${{ matrix.linter }}
